# Generated by Django 4.2.1 on 2025-03-14 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0002_alter_category_name_alter_records_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagpost',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tagposts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
